import { useState, useEffect } from "react";

export default function BalanceBall() {
  // Simulation state: tilt (–1 to 1), ball’s position (relative to platform center), and ball’s velocity.
    const [tilt, setTilt] = useState(0);
      const [ballX, setBallX] = useState(0);
        const [ballVelocity, setBallVelocity] = useState(0);

          const platformWidth = 200; // in pixels
            const accelerationFactor = 500; // adjust to change sensitivity

              // Update tilt when left/right arrow keys are pressed.
                useEffect(() => {
                    const handleKeyDown = (e) => {
                          if (e.key === "ArrowLeft") setTilt(-1);
                                else if (e.key === "ArrowRight") setTilt(1);
                                    };
                                        const handleKeyUp = (e) => {
                                              if (e.key === "ArrowLeft" || e.key === "ArrowRight") setTilt(0);
                                                  };
                                                      window.addEventListener("keydown", handleKeyDown);
                                                          window.addEventListener("keyup", handleKeyUp);
                                                              return () => {
                                                                    window.removeEventListener("keydown", handleKeyDown);
                                                                          window.removeEventListener("keyup", handleKeyUp);
                                                                              };
                                                                                }, []);

                                                                                  // Game loop using requestAnimationFrame.
                                                                                    useEffect(() => {
                                                                                        let animationFrameId;
                                                                                            let lastTime = performance.now();

                                                                                                const update = (time) => {
                                                                                                      const delta = (time - lastTime) / 1000; // seconds
                                                                                                            lastTime = time;

                                                                                                                  // Physics: acceleration from tilt affects velocity, which updates ball position.
                                                                                                                        const acceleration = tilt * accelerationFactor;
                                                                                                                              const newVelocity = ballVelocity + acceleration * delta;
                                                                                                                                    const newBallX = ballX + newVelocity * delta;

                                                                                                                                          // Check if ball goes off the platform (bounds: -platformWidth/2 to platformWidth/2).
                                                                                                                                                if (newBallX < -platformWidth / 2 || newBallX > platformWidth / 2) {
                                                                                                                                                        alert("Game Over!");
                                                                                                                                                                setBallX(0);
                                                                                                                                                                        setBallVelocity(0);
                                                                                                                                                                              } else {
                                                                                                                                                                                      setBallX(newBallX);
                                                                                                                                                                                              setBallVelocity(newVelocity);
                                                                                                                                                                                                    }
                                                                                                                                                                                                          animationFrameId = requestAnimationFrame(update);
                                                                                                                                                                                                              };
                                                                                                                                                                                                                  animationFrameId = requestAnimationFrame(update);
                                                                                                                                                                                                                      return () => cancelAnimationFrame(animationFrameId);
                                                                                                                                                                                                                        }, [tilt, ballX, ballVelocity]);

                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                              <div className="flex flex-col items-center mt-10">
                                                                                                                                                                                                                                    <h1 className="text-2xl font-bold">Balance the Ball</h1>
                                                                                                                                                                                                                                          <p className="mt-2">Use left/right arrow keys to tilt the platform.</p>
                                                                                                                                                                                                                                                <div className="relative bg-gray-200" style={{ width: "400px", height: "400px" }}>
                                                                                                                                                                                                                                                        {/* Platform */}
                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                          className="absolute bg-blue-500"
                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                width: "200px",
                                                                                                                                                                                                                                                                                                            height: "10px",
                                                                                                                                                                                                                                                                                                                        left: "100px", // centers the 200px wide platform in 400px container
                                                                                                                                                                                                                                                                                                                                    top: "350px",
                                                                                                                                                                                                                                                                                                                                                transform: `rotate(${tilt * 15}deg)`,
                                                                                                                                                                                                                                                                                                                                                            transformOrigin: "center",
                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                              ></div>
                                                                                                                                                                                                                                                                                                                                                                                      {/* Ball */}
                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                        className="absolute bg-red-500 rounded-full"
                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                              width: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                          height: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      left: `${200 + ballX - 10}px`, // platform center (200) plus offset, minus radius (10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: "340px", // adjust to sit on the platform
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }